# Generated by Django 4.2.10 on 2024-11-17 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORMS', '0003_meumodelo_produto_topic_cnpj_topic_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaUps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=10)),
                ('nome_ds', models.CharField(max_length=5)),
                ('potencia_ds', models.IntegerField()),
                ('imagem_ds', models.ImageField(upload_to='imagens/')),
                ('ups1', models.IntegerField()),
                ('potencia_ups1', models.IntegerField()),
                ('imagem_ups1', models.ImageField(upload_to='imagens/')),
                ('cod1', models.IntegerField()),
                ('energia_cod1', models.IntegerField()),
                ('imagem_cod1', models.ImageField(upload_to='imagens/')),
                ('imagem_cod1z', models.ImageField(upload_to='imagens/')),
                ('ups2', models.IntegerField()),
                ('potencia_ups2', models.IntegerField()),
                ('imagem_ups2', models.ImageField(upload_to='imagens/')),
                ('cod2', models.IntegerField()),
                ('energia_cod2', models.IntegerField()),
                ('imagem_cod2', models.ImageField(upload_to='imagens/')),
                ('imagem_cod2z', models.ImageField(upload_to='imagens/')),
                ('observacao', models.TextField(max_length=100)),
                ('nome_tecnico', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
