# Generated by Django 4.2.10 on 2024-11-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMS', '0004_salaups'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaups',
            name='energia_ete',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='salaups',
            name='energia_portaria',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='salaups',
            name='imagem_ete',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
        migrations.AddField(
            model_name='salaups',
            name='imagem_portaria',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
    ]
