# Generated by Django 4.2.10 on 2024-11-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMS', '0005_salaups_energia_ete_salaups_energia_portaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaups',
            name='energia_ete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaups',
            name='energia_portaria',
            field=models.IntegerField(default=0),
        ),
    ]
